AllCops:
  NewCops: disable
  Exclude:
    - vendor/**/*
    - .git/**/*
    - db/**/*
    - bin/*
    - config/*
    - config/**/*
    - lib/*
  TargetRubyVersion: 3.2

#################### Style ###########################

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

#################### Naming ##########################

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

#################### Metrics #########################

Metrics/AbcSize:
  Max: 17
  Exclude:
    - 'app/graphql/mutations/customer_mutations/create_customer.rb'
    - 'app/graphql/mutations/update_customer.rb'
    - 'app/graphql/mutations/login_mutations.rb'

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - '**/routes.rb'
    - 'config/**/*'
    - 'db/migrate/*.rb'
    - 'lib/tasks/**/*.rake'
    - '**/*_spec.rb'
    - 'spec/factories/**/*.rb'

Metrics/BlockNesting:
  CountBlocks: false
  Max: 3

Metrics/ClassLength:
  CountComments: false
  Max: 350

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:

Metrics/MethodLength:
  CountComments: false
  Max: 14
  Exclude:
    - 'app/graphql/mutations/login_mutations.rb'

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/PerceivedComplexity:
  Max: 8

##################### Layout ##########################

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoreCopDirectives: true

