default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: app_development_db

test:
  <<: *default
  database: app_test_db

production:
  <<: *default
  database: app_production_db
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
